package boundary;

import control.SCV;
import domain.Cliente;
import domain.Emprestimo;
import domain.Filme;
import domain.Fita;
import domain.ItemDeEmprestimo;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rafael
 */
public class FrmEmprestarFitas extends javax.swing.JInternalFrame {

    private DefaultListModel listModel;
    private Cliente cliente;
    private Emprestimo emprestimoCorrente = new Emprestimo();

    /**
     * Creates new form FrmEmprestarFitas
     */
    public FrmEmprestarFitas() {
        initComponents();

        //emprestimoCorrente.setItemDeEmprestimo(new ArrayList());

        //Instanciando jListFitas
        listModel = new DefaultListModel();

        //Carregando jComboBoxClientes
        ArrayList<Cliente> clientes = new ArrayList();
        clientes = SCV.selecionarTodosClientes();

        for (Cliente cliente : clientes) {
            this.jComboBoxClientes.addItem(cliente);
        }

        //Carregando jComboBoxFilmes
        ArrayList<Filme> filmes = new ArrayList();
        filmes = SCV.selecionarTodosFilmes();

        for (Filme filme : filmes) {
            this.jComboBoxFilmes.addItem(filme);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConfirmarFilme = new javax.swing.JButton();
        jComboBoxFilmes = new javax.swing.JComboBox();
        jButtonConfirmar = new javax.swing.JButton();
        jLabelFitasEmprestadas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFita = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jComboBoxClientes = new javax.swing.JComboBox();
        jButtonAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFitas = new javax.swing.JList();
        jComboBoxFitas = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tela de Registro de Empréstimo");

        jButtonConfirmarFilme.setText("Confirmar");
        jButtonConfirmarFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmarFilmeMouseClicked(evt);
            }
        });
        jButtonConfirmarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarFilmeActionPerformed(evt);
            }
        });

        jComboBoxFilmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar Filme" }));

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmarMouseClicked(evt);
            }
        });
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jLabelFitasEmprestadas.setText("Fitas Emprestadas");

        jLabel2.setText("Filme");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Formulário de Empréstimo de Fitas");

        jLabelFita.setText("Fita");

        jLabelCliente.setText("Cliente");

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Cliente" }));

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdicionarMouseClicked(evt);
            }
        });
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListFitas);

        jComboBoxFitas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a Fita" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFitasEmprestadas)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonConfirmar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCancelar))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFita)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBoxFitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAdicionar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmarFilme)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmarFilme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFita)
                    .addComponent(jButtonAdicionar)
                    .addComponent(jComboBoxFitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFitasEmprestadas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmarFilmeMouseClicked
    }//GEN-LAST:event_jButtonConfirmarFilmeMouseClicked

    private void jButtonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmarMouseClicked
    }//GEN-LAST:event_jButtonConfirmarMouseClicked

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        // TODO adicione seu c�digo de manipula��o aqui:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicionarMouseClicked
    }//GEN-LAST:event_jButtonAdicionarMouseClicked

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        //Obtendo a fita selecionada
        Fita fita = new Fita();
        fita = (Fita) this.jComboBoxFitas.getSelectedItem();

        ItemDeEmprestimo itemDeEmprestimo = new ItemDeEmprestimo();
        itemDeEmprestimo.setFita(fita);

        this.emprestimoCorrente.adicionarItemDeEmprestimo(itemDeEmprestimo);

        //Adicionando a Fita no DefaultListModel
        listModel.addElement(fita);
        //Setando o DefaultListModel no jListFitas
        //Ele irá atualizar automaticamente o jListFitas
        jListFitas.setModel(listModel);

        //Obtendo o cliente selecionado
        this.cliente = (Cliente) this.jComboBoxClientes.getSelectedItem();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        this.emprestimoCorrente.setCliente(this.cliente);

        //Chamando o método da Controladora responsável por inserir um empréstimo
        if (SCV.inserirEmprestimo(this.emprestimoCorrente)) {
            //Cliente Inserido com Sucesso
            JOptionPane.showMessageDialog(this, "Empréstimo Inserido com Sucesso!");
            //Limpando o Formulário de Inserção
            this.dispose();
        } else {
            //Falha na Inserção do Cliente
            JOptionPane.showMessageDialog(this, "Falha na Inserção do Empréstimo!");
            //Limpando o Formulário de Inserção
            this.dispose();
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonConfirmarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarFilmeActionPerformed
        this.jComboBoxFitas.removeAllItems();

        //Carregando jComboBoxFitas
        ArrayList<Fita> fitas = new ArrayList();
        Filme filme = new Filme();
        filme = (Filme) this.jComboBoxFilmes.getSelectedItem();
        fitas = SCV.selecionarFitasPorFilme(filme);
        for (Fita fita : fitas) {
            this.jComboBoxFitas.addItem(fita);
        }
    }//GEN-LAST:event_jButtonConfirmarFilmeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonConfirmarFilme;
    private javax.swing.JComboBox jComboBoxClientes;
    private javax.swing.JComboBox jComboBoxFilmes;
    private javax.swing.JComboBox jComboBoxFitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelFita;
    private javax.swing.JLabel jLabelFitasEmprestadas;
    private javax.swing.JList jListFitas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
