package boundary;

import control.SCV;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdbc.ConnectionFactory;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rafael
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    public FrmTelaPrincipal() {
        initComponents();

        //Abrindo conexão ( a única conexao da aplicacao )
        try {
            SCV.connection = ConnectionFactory.getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(FrmTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemInserirUF = new javax.swing.JMenuItem();
        jMenuItemInserirCidade = new javax.swing.JMenuItem();
        jMenuListagens = new javax.swing.JMenu();
        jMenuItemUF = new javax.swing.JMenuItem();
        jMenuCasosDeUso = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Videolocadora");

        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrosActionPerformed(evt);
            }
        });

        jMenuItemInserirUF.setText("UF");
        jMenuItemInserirUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInserirUFActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemInserirUF);

        jMenuItemInserirCidade.setText("Cidade");
        jMenuItemInserirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInserirCidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemInserirCidade);

        jMenuBar1.add(jMenuCadastros);

        jMenuListagens.setText("Listagens");
        jMenuListagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListagensActionPerformed(evt);
            }
        });

        jMenuItemUF.setText("UF");
        jMenuItemUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUFActionPerformed(evt);
            }
        });
        jMenuListagens.add(jMenuItemUF);

        jMenuBar1.add(jMenuListagens);

        jMenuCasosDeUso.setText("Casos de Uso");

        jMenuItem1.setText("Registrar Empréstimo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCasosDeUso.add(jMenuItem1);

        jMenuBar1.add(jMenuCasosDeUso);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmEmprestarFitas objTelaEmprestarFitas = new FrmEmprestarFitas();
        this.jDesktopPane1.add(objTelaEmprestarFitas);
        objTelaEmprestarFitas.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuListagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListagensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuListagensActionPerformed

    private void jMenuItemInserirUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInserirUFActionPerformed
        FrmInserirUF objTelaInserirUF = new boundary.FrmInserirUF();
        this.jDesktopPane1.add(objTelaInserirUF);
        objTelaInserirUF.show();
    }//GEN-LAST:event_jMenuItemInserirUFActionPerformed

    private void jMenuItemInserirCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInserirCidadeActionPerformed
        FrmInserirCidade objTelaInserirCidade = new boundary.FrmInserirCidade();
        this.jDesktopPane1.add(objTelaInserirCidade);
        objTelaInserirCidade.show();
    }//GEN-LAST:event_jMenuItemInserirCidadeActionPerformed

    private void jMenuItemUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUFActionPerformed
        FrmListarUF objTelaListarUF = new boundary.FrmListarUF();
        this.jDesktopPane1.add(objTelaListarUF);
        objTelaListarUF.show();
    }//GEN-LAST:event_jMenuItemUFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuCasosDeUso;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemInserirCidade;
    private javax.swing.JMenuItem jMenuItemInserirUF;
    private javax.swing.JMenuItem jMenuItemUF;
    private javax.swing.JMenu jMenuListagens;
    // End of variables declaration//GEN-END:variables
}
